# SQLite version 3.x changed to postgresql
#   gem install postgresql
#
#   Ensure the postgresql gem is defined in your Gemfile
#   gem 'postgresql'
#

default: &default
  adapter: postgresql
  encoding: unicode
  # username: ubuntu
  pool: 5

development:
  <<: *default
  database: my_database_development
  timeout: 5000

test:
  <<: *default
  database: my_database_test
  timeout: 5000

production:
  <<: *default
  database: my_database_production
  timeout: 5000