# SQLite version 3.x changed to postgresql
#   gem install postgresql
#
#   Ensure the postgresql gem is defined in your Gemfile
#   gem 'postgresql'
#
development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000