# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa28945600beea14c04e97e015f40040986f9149d3779a00db0c17a9d8545e35414e1cf0ebc4db598460caa5bf2e80874e885122be66ff6437365557785ed4b8

test:
  secret_key_base: c1bf00959b4671bbd603b678f4d6318e01f5fc4e8d551c824f8113f79c76b9847d24b38e2b88d4c98fcb817b6905fe72422f768b4f1a6b09b68d8f154aaecd09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
