class AddQuestionsToEvents < ActiveRecord::Migration
  	def change
  	add_column :events, :Q1, :string
  	add_column :events, :Q2, :string
  	add_column :events, :Q3, :string
  	add_column :events, :Q4, :string
  	add_column :events, :Q5, :string
  	add_column :events, :Q6, :string
  	add_column :events, :Q7, :string
  	add_column :events, :Q8, :string
  	add_column :events, :Q9, :string
  	add_column :events, :Q10, :string
  	add_column :events, :Q11, :string
  	add_column :events, :Q12, :string
  	add_column :events, :Q13, :string
  	add_column :events, :Q14, :string
  	add_column :events, :Q15, :string
  	add_column :events, :Q16, :string
  	add_column :events, :Q17, :string
  	add_column :events, :Q18, :string
  	add_column :events, :Q19, :string
  	add_column :events, :Q20, :string
  	add_column :events, :Q21, :string
  	add_column :events, :Q22, :string
  	add_column :events, :Q23, :string
  	add_column :events, :Q24, :string
  	add_column :events, :Q25, :string
  	add_column :events, :Q26, :string
  	add_column :events, :Q27, :string
  	add_column :events, :Q28, :string
  	add_column :events, :Q29, :string
  	add_column :events, :Q30, :string
  	add_column :events, :Q31, :string
  	add_column :events, :Q32, :string
  	add_column :events, :Q33, :string
  	add_column :events, :Q34, :string
  	add_column :events, :Q35, :string
  	add_column :events, :Q36, :string
  	add_column :events, :Q37, :string
  	add_column :events, :Q38, :string
  	add_column :events, :Q39, :string
  	add_column :events, :Q40, :string
  	add_column :events, :Q41, :string
  	add_column :events, :Q42, :string
  	add_column :events, :Q43, :string
  	add_column :events, :Q44, :string
  	add_column :events, :Q45, :string
  	add_column :events, :Q46, :string
  	add_column :events, :Q47, :string
  	add_column :events, :Q48, :string
  	add_column :events, :Q49, :string
  	add_column :events, :Q50, :string
  	add_column :events, :Q51, :string
  	add_column :events, :Q52, :string
  	add_column :events, :Q53, :string
  	add_column :events, :Q54, :string
  	add_column :events, :Q55, :string
  	add_column :events, :Q56, :string
  	add_column :events, :Q57, :string
  	add_column :events, :Q58, :string
  	add_column :events, :Q59, :string
  	add_column :events, :Q60, :string
  	add_column :events, :Q61, :string
  	add_column :events, :Q62, :string
  	add_column :events, :Q63, :string
  	add_column :events, :Q64, :string
  	add_column :events, :Q65, :string
  	add_column :events, :Q66, :string
  	add_column :events, :Q67, :string
  	add_column :events, :Q68, :string
  	add_column :events, :Q69, :string
  	add_column :events, :Q70, :string
  	add_column :events, :Q71, :string
  	add_column :events, :Q72, :string
  	add_column :events, :Q73, :string
  	add_column :events, :Q74, :string
  	add_column :events, :Q75, :string
  	add_column :events, :Q76, :string
  	add_column :events, :Q77, :string
  	add_column :events, :Q78, :string
  	add_column :events, :Q79, :string
  	add_column :events, :Q80, :string
  	add_column :events, :Q81, :string
  	add_column :events, :Q82, :string
  	add_column :events, :Q83, :string
  	add_column :events, :Q84, :string
  	add_column :events, :Q85, :string
  	add_column :events, :Q86, :string
  	add_column :events, :Q87, :string
  	add_column :events, :Q88, :string
  	add_column :events, :Q89, :string
  	add_column :events, :Q90, :string
  	add_column :events, :Q91, :string
  	add_column :events, :Q92, :string
  	add_column :events, :Q93, :string
  	add_column :events, :Q94, :string
  	add_column :events, :Q95, :string
  	add_column :events, :Q96, :string
  	add_column :events, :Q97, :string
  	add_column :events, :Q98, :string
  	add_column :events, :Q99, :string
  	add_column :events, :Q100, :string
  	add_column :events, :Q101, :string
  	add_column :events, :Q102, :string
  	add_column :events, :Q103, :string
  	add_column :events, :Q104, :string
  	add_column :events, :Q105, :string
  	add_column :events, :Q106, :string
  	add_column :events, :Q107, :string
  	add_column :events, :Q108, :string
  	add_column :events, :Q109, :string
  	add_column :events, :Q110, :string
  	add_column :events, :Q111, :string
  	add_column :events, :Q112, :string
  	add_column :events, :Q113, :string
  	add_column :events, :Q114, :string
  	add_column :events, :Q115, :string
  	add_column :events, :Q116, :string
  	add_column :events, :Q117, :string
  	add_column :events, :Q118, :string
  	add_column :events, :Q119, :string
  	add_column :events, :Q120, :string
  end
end
